backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:

  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    fields:
      - {label: "Project Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
